/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as LoginLayoutImport } from "./routes/login/_layout"
import { Route as AuthLayoutImport } from "./routes/_auth/_layout"
import { Route as LoginLayoutIndexImport } from "./routes/login/_layout/index"
import { Route as LoginLayoutGetTokenImport } from "./routes/login/_layout/getToken"

// Create Virtual Routes

const LoginImport = createFileRoute("/login")()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route))

const LoginLayoutRoute = LoginLayoutImport.update({
  id: "/_layout",
  getParentRoute: () => LoginRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: "/_auth/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LoginLayoutIndexRoute = LoginLayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LoginLayoutRoute,
} as any)

const LoginLayoutGetTokenRoute = LoginLayoutGetTokenImport.update({
  id: "/getToken",
  path: "/getToken",
  getParentRoute: () => LoginLayoutRoute,
} as any).lazy(() =>
  import("./routes/login/_layout/getToken.lazy").then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/_auth/_layout": {
      id: "/_auth/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/login/_layout": {
      id: "/login/_layout"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginLayoutImport
      parentRoute: typeof LoginRoute
    }
    "/login/_layout/getToken": {
      id: "/login/_layout/getToken"
      path: "/getToken"
      fullPath: "/login/getToken"
      preLoaderRoute: typeof LoginLayoutGetTokenImport
      parentRoute: typeof LoginLayoutImport
    }
    "/login/_layout/": {
      id: "/login/_layout/"
      path: "/"
      fullPath: "/login/"
      preLoaderRoute: typeof LoginLayoutIndexImport
      parentRoute: typeof LoginLayoutImport
    }
  }
}

// Create and export the route tree

interface LoginLayoutRouteChildren {
  LoginLayoutGetTokenRoute: typeof LoginLayoutGetTokenRoute
  LoginLayoutIndexRoute: typeof LoginLayoutIndexRoute
}

const LoginLayoutRouteChildren: LoginLayoutRouteChildren = {
  LoginLayoutGetTokenRoute: LoginLayoutGetTokenRoute,
  LoginLayoutIndexRoute: LoginLayoutIndexRoute,
}

const LoginLayoutRouteWithChildren = LoginLayoutRoute._addFileChildren(
  LoginLayoutRouteChildren,
)

interface LoginRouteChildren {
  LoginLayoutRoute: typeof LoginLayoutRouteWithChildren
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLayoutRoute: LoginLayoutRouteWithChildren,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "": typeof AuthLayoutRoute
  "/login": typeof LoginLayoutRouteWithChildren
  "/login/getToken": typeof LoginLayoutGetTokenRoute
  "/login/": typeof LoginLayoutIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "": typeof AuthLayoutRoute
  "/login": typeof LoginLayoutIndexRoute
  "/login/getToken": typeof LoginLayoutGetTokenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/_auth/_layout": typeof AuthLayoutRoute
  "/login": typeof LoginRouteWithChildren
  "/login/_layout": typeof LoginLayoutRouteWithChildren
  "/login/_layout/getToken": typeof LoginLayoutGetTokenRoute
  "/login/_layout/": typeof LoginLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "" | "/login" | "/login/getToken" | "/login/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "" | "/login" | "/login/getToken"
  id:
    | "__root__"
    | "/"
    | "/_auth/_layout"
    | "/login"
    | "/login/_layout"
    | "/login/_layout/getToken"
    | "/login/_layout/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  LoginRoute: typeof LoginRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  LoginRoute: LoginRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth/_layout": {
      "filePath": "_auth/_layout.tsx"
    },
    "/login": {
      "filePath": "login",
      "children": [
        "/login/_layout"
      ]
    },
    "/login/_layout": {
      "filePath": "login/_layout.tsx",
      "parent": "/login",
      "children": [
        "/login/_layout/getToken",
        "/login/_layout/"
      ]
    },
    "/login/_layout/getToken": {
      "filePath": "login/_layout/getToken.tsx",
      "parent": "/login/_layout"
    },
    "/login/_layout/": {
      "filePath": "login/_layout/index.tsx",
      "parent": "/login/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
